version: "3"

services:
  crypto-trading:
    image: binance-diy-bot:3
    container_name: binance_diy_bot
    working_dir: /app
    volumes:
      - ./user.cfg:/app/user.cfg
      - ./supported_coin_list:/app/supported_coin_list
      - ./data:/app/data
      - ./logs:/app/logs
    command: python -m binance_trade_bot
    environment:
      - PYTHONUNBUFFERED=1
