version: "3"

services:
  crypto-trading:
    image: izsakniko/binance-bot:4.0
    container_name: binance_diy_bot_v4
    working_dir: /app
    volumes:
      - /volume1/docker/binance-bot-v4/user.cfg:/app/user.cfg
      - /volume1/docker/binance-bot-v4/supported_coin_list:/app/supported_coin_list
      - /volume1/docker/binance-bot-v4/data:/app/data
      - /volume1/docker/binance-bot-v4/logs:/app/logs
      - /volume1/docker/binance-bot-v4/config:/app/config
    command: python -m binance_trade_bot
    environment:
      - PYTHONUNBUFFERED=1